### ISSUE TITLE
Accept empty startup-scripts

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#107]
When debugging it's convenient to comment out script invocations from some of the sections like `startup-scripts`: however qDup fails to parse this as it expects list and in this case it is resolved as mapping with empty scalar value.

Naturally I can change it to `startup-scripts: []` but it'd be more convenient if I did not have to alter that line.

**Comment by willr3** [comment]
`setup-scripts` can be omitted if you want to comment out all the setup-scripts from a role.
```yaml
roles:
  test:
#  - setup-scripts:
#    - first
  - run-scripts:
    doit
```
We can add the change to the yaml parser to support an empty string. My concern is that we are adding a corner cases to yaml parsing that make it more difficult to maintain. What do you think about adding corner cases to yaml parsing? How have you approached it in hyperfoil?
