### ISSUE TITLE
set-default command

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#160]
For convenience and less repetitiveness it would be useful to add command
```
- set-default: FOO bar
```
that would be equivalent to
```
- set-state: FOO ${{FOO:bar}}
```

**Comment by willr3** [comment]
I do not think we should add commands that already have an equivalent one line command. I understand the appeal of a more descriptive syntax but we have talked about limiting the number of commands to make it easier for user to learn all of the qDup functionality. 
I think we are better suited to be selective when adding commands and instead add examples and how tos to illustrate best practices like the one you mention here.

**Comment by rvansa** [comment]
Fair enough, I'll close this then.
