### ISSUE TITLE
unreadable log after using secret states (the ones prefixed by underscore)

### ISSUE THREAD

**Issue by vitorz** [Hyperfoil/qDup#182]
After the introduction of **_secret_** states for holding some passwords in a **_qdup_** file, most of the log messages are unreadable and huge. It's just a log issue as all the rest looks working to me.
The log messages look in this way:
`***************e********************************************************************************r**************************************`

**Comment by vitorz** [comment]
this happens if the secret is loaded as empty string.

**Comment by johnaohara** [comment]
@vitorz thanks for getting to the bottom of this, I will re-open as this is an issue that renders the entire log unreadable

**Comment by vitorz** [comment]
The strange point is that the cause is the missing of values for the secrets in the `states` section of `qdup.yaml`. Although at runtime some values are supplied for secrets, the former reason causes the issue. At code level i guess the right place to watch is the filter method of `SecretFilter` class as the `String.replace` used there can causes this issue if  the first parameter is an empty string.

**Comment by willr3** [comment]
It sounds like there are two issues:
1. The `SecretFilter` should not add an empty string as a secret. 
2. Secret values that contain other secret values need to be checked first to prevent exposing part of the longer secret.

[anything we think I missed?](https://github.com/Hyperfoil/qDup/compare/master...willr3:qDup:secrets-182)

**Comment by vitorz** [comment]
Hi, thanks for fixing. Nothing is missing for me.

**Comment by willr3** [comment]
closing as we merged the fix for the secretsfilter
