### ISSUE TITLE
Introduce pause/breakpoint cmd

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#32]
It would be useful to have a way of enabling pausing of scripts during a qDup run. 

Either with a pause: or breakpoint: command, or a global switch command line switch that pauses script execution on all signal: commands

At the moment, if there is a problem with a script, the only method of debugging is to manually recreate the steps that cause the issue, or to alter scripts by commenting out sections or removing signal/wait-for commands.

A global method for enabling breakpoints in scripts would enable users to debug issues without having to alter scripts

**Comment by willr3** [comment]
`-K,--breakpoint <breakpoint>`
Tells qDup to compare breakpoint (as a substring or java regex) to the string representation of each command and if it matches it will pause that script until you hit enter in the terminal. This does not pause execution of other scripts. Do you want it to pause all scripts?

**Comment by willr3** [comment]
Closing assuming `--breakpoint` meets the need
