### ISSUE TITLE
Intermittent out of order execution of scripts

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#52]
This  issue only manifests intermittently.  I am not sure if there is a race condition on the signal or the state. This needs further investigation.

I enabled logging of failures when populating patterns in scripts, see https://github.com/Hyperfoil/qDup/pull/51

Whilst this exposed some incorrect script definitions, one behaviour that has become apparent is that sometimes scripts are run out of order when flow is controlled by signals. e.g.

![mermaid-diagram-20200203095140](https://user-images.githubusercontent.com/959822/73643101-cdb6ac00-466a-11ea-9494-2926c85dc1ec.png)

Occasionally, `ReadStats` appears to try and read the state before `CaptureStats` signals the state variable has been written to

This results in message logged such as, because the state is not available in the state map ;

```
11:20:55.554 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.started
                       ^

11:20:55.592 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.first_request
                       ^

11:20:55.616 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.warm
                       ^

11:20:55.647 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.throughput
                       ^

11:20:55.665 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.latencyAvg
                       ^

11:20:55.681 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.latencyStddev
                       ^

11:20:55.698 push-stats@test:SyntaxError: Unnamed:1:23 Expected ; but found .1
RUN.getting-started.jvm.1.latencyMax

```

**Comment by rvansa** [comment]
Out of date?

**Comment by johnaohara** [comment]
I have not seen this issue for a long time, we can close as out of date
