### ISSUE TITLE
-S ignores empty values and uses ! to delete

### ISSUE THREAD

**Issue by willr3** [Hyperfoil/qDup#61]
Change the command line state injection to ignore state with empty values and to require `-S !FOO` to explicitly remove FOO from the state

**Comment by willr3** [comment]
Is there a case where an empty string is an appropriate value?

**Comment by willr3** [comment]
! is a special character in bash. it is used to refer to a previous command in local command history. What do we think about a value that means delete the entry?
` -S foo=_` 
we already use `_` as a key prefix to indicate the value should be suppressed from logs.

**Comment by willr3** [comment]
@rvansa @johnaohara 
What do you think about `-SX key` or `-XS key` to explicitly delete a state entry? `!` is a special bash character and I cannot find how to pass it as the start of the key name in the terminal.

**Comment by rvansa** [comment]
Sure, I didn't realize it's a special character. `-SX key` sounds good.

Btw does qDup make any difference between unset variables and empty ones? (I guess not)

**Comment by willr3** [comment]
It depends on what you mean by unset versus empty?
```yaml
states:
  unset: 
  empty: ""
```
those should both result in an empty string value for the state keys.
```yaml
- sh: ${{FOO}}
```
In this case there is a difference. If `FOO` is not defined in the `states` then it will abort but if `FOO` is an empty string in `states` then it will not abort because sometimes an empty string is the desired substitution.

**Comment by rvansa** [comment]
That's what I meant. The same behaviour of `unset` and `empty` is kind of mandated by YAML semantics.

So should this `-SX key` completely unset it (cause abort upon use) or just set it to empty value?

Is there a way to unset variable in `set-state`?

**Comment by willr3** [comment]
That is a great point! My gut is that `-SX` should set it to an empty value. I doubt a user would want `-SX` to fully remove the state and potentially cause scripts to abort.
`set-state` can change a state to an empty string but it cannot remove the entry from `states`. `${{FOO:bar}}` will return `bar` if the value of `FOO` is an empty string and `${{FOO}}` will return an empty string. There is also `read-state: ${{FOO}}` which returns that output of the substitution as the input to the `then` commands but will skip the `then` commands if the result is an empty string.
```yaml
- read-state: ${{jfrProfile}}
  then:
  - sh: add jfrProfile to java_opts
```
This way the jfr args are only added to java_opts if there is a jfrProfile specified

**Comment by rvansa** [comment]
Already implemented I think.
