### ISSUE TITLE
Server documentation out of date

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/qDup#66]
e.g. `/latches` was replaced by `/signal`...

**Comment by willr3** [comment]
I updated the README with more of the JsonServer's api. 
Documentation is definitely first on the todo list now that reconnect appears to work

**Comment by rvansa** [comment]
Thanks. I would also print the endpoints when hitting root, so that I don't have to lookup GitHub (and can just do `curl myhost:31337` - as long as I remember the port number.
