### ISSUE TITLE
Javascript spread operator is not being evaluated in JS set-state expression

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/qDup#73]
The following `set-state` command is not being expanded correctly;

`- set-state: RUN.${{SCOMBO}}.warm ${{=[...${{RUN.${{SCOMBO}}.warm}} , ${{WARM}}]}}`

output;

`set-state: RUN.config-quickstart.JVM.4.warm =[...${{RUN.${{SCOMBO}}.warm}} , 336384]`

**Comment by willr3** [comment]
This should be fixed with updating yaup to 0.8.4. Please re-open if it isn't working correctly

**Comment by johnaohara** [comment]
ty
